"""fix

Revision ID: b17a72cd764d
Revises: d34b440b9326
Create Date: 2024-12-22 14:51:37.048191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17a72cd764d'
down_revision: Union[str, None] = 'd34b440b9326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###
